### ISSUE TITLE
Some errors in the description

### ISSUE THREAD

**Issue by Mingo12** [rjnorthrow/amiga-internet#1]
Hi

I have successfully connected the amiga to the Raspberry Pi and opened a few Websites. But i have found some errors in the description that should be corrected:

Wrong Linux comand:
"ansible-galaxy install rjnorthrow.ppp_amiga" should be "ansible-galaxy install rjnorthrow.amiga_ppp".

Wrong comand on the Amiga:
"ed SYS:Internet/bin/startnet" should be "ed SYS:Internet/AmiTCP-3.0b2/bin/startnet".

Also it should be mentoined, that a NullModem cable and a serial adatper (25 to 9 pin) ist required. 

And last but not least, the amiga need more than 2Mb RAM. I used a bare Amiga 1200 with fresh installed OS3, AmiTCP and the Voyager Browser. When i open a Website, the Memory is almost depleded.

I hope i could help with this. 
Keep up this great Project!

**Comment by rjnorthrow** [comment]
Great, thanks very much for the corrections! I'll apply those now ...

**Comment by rjnorthrow** [comment]
Corrections applied.
